spring:
  application:
    name: rest-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api?userTimezone=true&serverTimezone=UTC
    username: root
    password: 2!TDYqb%230S
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: false
    open-in-view: false
  devtools:
    add-properties: false
logging:
  level:
    #root: DEBUG
    com.gusferreirac.rest_api: DEBUG

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true